development:
  adapter: mysql2
  database: ip_development
  host: localhost
  username: root
  
test:
  adapter: mysql2
  database: ip_test
  host: localhost
  username: root

production:
  adapter: mysql2
  database: ip_production
  host: localhost
  username: root
